version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /opt/ceybankrest/backend
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
