services:
  mysql:
    image: mysql:8.0
    container_name: ceybank_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ceybank
      MYSQL_USER: ceybank_user
      MYSQL_PASSWORD: ceybank_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    image: docker.io/pamitha/ceybank:latest
    container_name: ceybank_app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ceybank?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ceybank_user
      SPRING_DATASOURCE_PASSWORD: ceybank_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
 db_data:



